{
  pkgs,
  osConfig,
  config,
  lib,
  ...
}:
let
  # Vendored from https://themes.neomutt.org (neomutt/themes, truecolor/
  # "Nord Wave.rc") - re-copy from upstream if it changes.
  nordWave = ../../config/neomutt/nord-wave.rc;

  # Vim-style keybindings, ported from
  # https://ryanlue.com/posts/2017-05-21-mutt-the-vim-way
  vimBindings = ../../config/neomutt/vim-bindings.rc;

  # Sidebar mailboxes. The tags they filter on are assigned by
  # config/notmuch/hooks/post-new, which is kept out of nix on purpose so that
  # retagging mail is one `notmuch new` away, not a system rebuild.
  inboxQuery = "folder:/INBOX$/ and not tag:noise";
  virtualMailboxes = [
    {
      name = "INBOX";
      query = inboxQuery;
    }
    {
      name = "Nordaaker";
      query = "tag:nordaaker and not tag:bulk";
    }
    {
      name = "Nordaaker/Bulk";
      query = "tag:nordaaker and tag:bulk";
    }
    {
      name = "GitHub";
      query = "tag:github";
    }
    {
      name = "LinkedIn";
      query = "tag:linkedin";
    }
    {
      name = "Lists";
      query = "tag:list";
    }
    {
      name = "Signups";
      query = "tag:signups";
    }
    {
      name = "Receipts";
      query = "tag:receipts";
    }
    {
      name = "Cloudflare";
      query = "tag:cloudflare";
    }
    {
      name = "DMARC";
      query = "tag:dmarc";
    }
    {
      name = "Digests";
      query = "tag:digests";
    }
    {
      name = "Finn";
      query = "tag:finn";
    }
    {
      name = "Promo";
      query = "tag:promo";
    }
  ];
in
{
  # means.no is hosted as a custom domain on iCloud Mail, so the iCloud
  # IMAP/SMTP endpoints and an app-specific password (secrets/email-password.age)
  # are what applies here.
  accounts.email = {
    maildirBasePath = "Mail";
    accounts.means = {
      address = "marcus@means.no";
      realName = "Marcus Ramberg";
      # iCloud authenticates with the bare Apple username, not the mailbox
      # address (verified against imap/smtp.mail.me.com).
      userName = "marcus.ramberg";
      primary = true;
      passwordCommand = "${pkgs.coreutils}/bin/cat ${osConfig.age.secrets.email-password.path}";

      imap = {
        host = "imap.mail.me.com";
        port = 993;
        tls.enable = true;
      };
      smtp = {
        host = "smtp.mail.me.com";
        port = 587;
        tls.enable = true;
        tls.useStartTls = true;
      };

      # Names as advertised by iCloud's IMAP LIST.
      folders = {
        inbox = "INBOX";
        sent = "Sent Messages";
        drafts = "Drafts";
        trash = "Deleted Messages";
      };

      mbsync = {
        enable = true;
        # iCloud creates folders on the fly; without this mbsync refuses to open
        # near-side boxes that do not exist locally yet.
        extraConfig.channel = {
          Create = "both";
        };
      };
      msmtp.enable = true;
      neomutt = {
        enable = true;
        sendMailCommand = "${pkgs.msmtp}/bin/msmtp --read-envelope-from --read-recipients";
        # The notmuch "INBOX" virtual folder below replaces it.
        showDefaultMailbox = false;
      };
      notmuch = {
        enable = true;
        neomutt.virtualMailboxes = virtualMailboxes;
      };
    };
  };

  # Own hook, symlinked like config/nvim rather than generated by home-manager.
  home.file.".config/notmuch/default/hooks".source =
    config.lib.file.mkOutOfStoreSymlink "/etc/nixos/config/notmuch/hooks";

  home.packages = [ pkgs.w3m ];
  programs = {
    mbsync.enable = true;
    msmtp.enable = true;
    neomutt = {
      enable = true;
      vimKeys = true;
      sidebar = {
        enable = true;
        shortPath = true;
      };
      # Last thing sourced, so the notmuch view wins as the startup mailbox -
      # the plain +INBOX maildir holds everything, tags included.
      extraConfig = ''
        source ${nordWave}
        source ${vimBindings}
        set spoolfile = "notmuch://?query=${lib.escapeURL inboxQuery}"
      '';
      settings = {
        rfc2047_parameters = "yes";
        sleep_time = "0";
        # Show counts for folder
        mail_check_stats = "yes";
        mail_check_stats_interval = "30";
        delete = "yes";
      };
    };
    # Config file and package only; the tag rules live in the hook above.
    notmuch.enable = true;
  };

  services.mbsync = {
    enable = true;
    frequency = "*:0/5";
    # NOTMUCH_CONFIG is not part of the unit environment, and notmuch's profile
    # layout lives outside ~/.notmuch-config, so name the config file.
    postExec = "${pkgs.notmuch}/bin/notmuch --config ${config.xdg.configHome}/notmuch/default/config new";
  };
}
