when:
  event:
    - cron
    - push
    - manual

steps:
  - name: renovateDryRun
    image: renovate/renovate
    pull: true
    commands:
      - renovate $${CI_REPO}
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://code.bas.es
      LOG_LEVEL: debug
      RENOVATE_DRY_RUN: full
      GITHUB_COM_TOKEN:
        from_secret: github_token
      RENOVATE_TOKEN:
        from_secret: renovate_token
    when:
      - event: push
  - name: renovate
    image: renovate/renovate
    pull: true
    commands:
      - renovate $${CI_REPO}
    environment:
      RENOVATE_PLATFORM: gitea
      RENOVATE_ENDPOINT: https://code.bas.es
      RENOVATE_GIT_AUTHOR: renovate-bot <renovate@bas.es>
      RENOVATE_TOKEN:
        from_secret: renovate_token
      GITHUB_COM_TOKEN:
        from_secret: github_token
      LOG_LEVEL: debug
    when:
      - event: cron
        cron: renovate
      - event: manual
