labels:
  builder: x86
when:
  event:
    - pull_request
    - cron
steps:
  - name: chown
    image: alpine:latest
    commands:
      - chown -R nobody:noobdy .
  - name: update
    when:
      - event: cron
        cron: nightly
      - event: pull_request
      - path: flake.lock
    image: code.bas.es/bas.es/nixbuilder
    environment:
      ATTIC_TOKEN:
        from_secret: attic_token
    commands:
      - nix profile install nixpkgs#attic-client github:Mic92/nix-fast-build
      - attic login local https://cache.bas.es/ $ATTIC_TOKEN
      - attic use bases
      - nix-fast-build --attic bases -f .#devShells.x86_64-linux.default --no-nom --skip-cached --no-link
      - nix-fast-build --attic bases -f .#nixosConfigurations.mdeck.config.system.build.toplevel --no-nom --skip-cached --no-link

    volumes:
      - /mnt/nix:/nix
