labels:
  builder: x86
when:
  event:
    - pull_request
    - cron
steps:
  - name: chown
    image: alpine:latest
    commands:
      - chown -R 65534:65534 .
  - name: update
    when:
      - event: cron
        cron: nightly
      - event: pull_request
      - path: flake.lock
    image: code.bas.es/bas.es/nixbuilder
    environment:
      ATTIC_TOKEN:
        from_secret: attic_token
    commands:
      - nix develop .#update -c './build-cache.sh'

    volumes:
      - /mnt/nix:/nix
