when:
  event:
    - pull_request
    - cron
steps:
  - name: update
    when:
      - event: cron
        cron: nightly
      - event: pull_request
      - path: flake.lock
    image: nixos/nix
    environment:
      ATTIC_TOKEN:
        from_secret: attic_token
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - echo 'extra-substituters = https://cache.bas.es/bases' >> /etc/nix/nix.conf
      - echo 'extra-trusted-public-keys =  bases:bg7mtzwSME8dI+IXhYLzDTQ4TzY4zMmIzyeqjgR5Isg=' >> /etc/nix/nix.conf
      - nix profile add nixpkgs#attic-client
      - attic login local https://cache.bas.es/ $ATTIC_TOKEN
      - attic use bases
      - nix build .#nixosConfigurations.mdeck.config.system.build.toplevel
      - attic push bases ./result
      - nix build .#devShells.x86_64-linux.default
      - attic push bases ./result
    volumes:
      - /nix
