---
name: "Test"

"on":
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup push cache
        run: echo '{ cachix.push = "marcusramberg"; }' > devenv.local.nix
        shell: sh
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: marcusramberg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix develop --quiet --impure --command "devenv test"
