---
name: "Test"

"on":
  pull_request:
  push:


jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install github:cachix/devenv/v0.5
        shell: sh
      - run: devenv ci
      - run: devenv shell echo ok
